### ISSUE TITLE
500 Internal Server Error for POST /users/register

### ISSUE THREAD

**Issue by mickeymond** [FARM-CONNECT-GHANA/farm-connect-api#1]
@busolatom I am posting the following payload
```
{
    "firstName": "Michael",
    "lastName": "Hammond",
    "phone": "0248470214",
    "email": "mickeymond@yahoo.com",
    "password": "1234567890"
}
```
And I am getting the error below
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Error</title>
</head>

<body>
    <pre>Internal Server Error</pre>
</body>

</html>
```

**Comment by mickeymond** [comment]
@busolatom You can start by looking at the Render Deployment LOGs if there are any errors there.

**Comment by busolatom** [comment]
@mickeymond please the role field is also required to be enter as enum values of either farmer or customer, i just tested and confirmed the registration endpoint OK on my end, kindly try again

**Comment by mickeymond** [comment]
@busolatom I have noticed that but there needs to be required here https://github.com/FARM-CONNECT-GHANA/farm-connect-api/blob/main/utils/validation.js#L9 if the role field is really required.

**Comment by busolatom** [comment]
@mickeymond validation update done, thank you
