### ISSUE TITLE
500 Internal Server Error for GET /users/farmerprofile

### ISSUE THREAD

**Issue by mickeymond** [FARM-CONNECT-GHANA/farm-connect-api#2]
@busolatom Looks to me like this endpoint needs the **authenticated** middleware.
But please check.

**Comment by busolatom** [comment]
@mickeymond yes it does and i have it authenticated, i have GET /users/farmerprofile for the farmer and GET/users/farmerprofile/:id for public view with no authentication. please pull my recent commits
