### ISSUE TITLE
500 Internal Server Error for POST /users/farmerprofile

### ISSUE THREAD

**Issue by mickeymond** [FARM-CONNECT-GHANA/farm-connect-api#3]
@busolatom I am getting the error below
```
{
    "message": "An error occurred while creating the farmer profile"
}
```

I have to admit that I am not passing in any body but that should be handled gracefully by the Joi Validation.

What do you think?

**Comment by busolatom** [comment]
@mickeymond you are getting the error message i set in the create farmer profile controller, i don't have any of the farmer model fields required so joi won't prompt that the field is required, my current validator checks the input type if provided, i will now look into using joi to handle errors if no input is provided for profile creation

**Comment by busolatom** [comment]
@mickeymond i think changing the error message i set in my controller will fix this because i am not able to find how to use joi to handle no input error when the field is not required.... kindly advise, i have now changed the error message and pushed the commit

**Comment by mickeymond** [comment]
@busolatom I think the error is actually happening due to the **farmPhotos** remoteUpload.
Again, I am failing to upload files and that is what a Frontend might do so such an error needs to be handled well.
Let see if you can use the resource here to handle it https://expressjs.com/en/resources/middleware/multer.html#:~:text=Error%20handling,-When%20encountering%20an&text=If%20you%20want%20to%20catch,MulterError%20).

**Comment by busolatom** [comment]
@mickeymond i am surprised because i actually tested creating profile without and with photo uploads and both worked on my end, i will look into it again

**Comment by busolatom** [comment]
@mickeymond my code is such that it allows you pass whether you upload photo or not, you should not encounter any error for the remoteUpload, i just tested it again and it worked so i committed and pushed again, please pull and try again, thank you

**Comment by busolatom** [comment]
@mickeymond please pull my recent commits to test

**Comment by mickeymond** [comment]
@busolatom I can POST now but I just noticed that, posting several times results in multiple farmer profile creations.
If your intended goal is not to allow a farmer to create more than 1 profile, then you have to address this little BUG.
Confirm from your Database however if my observation is legitimate first.

**Comment by busolatom** [comment]
@mickeymond thank you for the observation and calling my attention to it, i have corrected the bug and pushed the commit just now, only one profile can be created per farmer

**Comment by mickeymond** [comment]
@busolatom This is excellent.
I was a BIT ahead of you before your deployment was completed on Render so you clear your farmerprofile collection if you still find duplicates from me.
